/* This file was automagically generated by autoconf */

/* 2 moves in 64 steps of size 16384 when reallocing */
#define NOpw_class
#define NOstrlcat
#define NOsetrgid
#define MAX_argc 7588
/* Your system's strstr() is 1.14 times SLOWER than my C-routine */
#define SLOWstrstr			      /* using my substitute instead */
#define UDP_protocolno 17
#define BIFF_serviceport "512"
#define IP_localhost {127,0,0,1}
#define MAILSPOOLDIR "/var/spool/mail/"
#define SENDMAIL "/usr/sbin/sendmail"
#define CF_no_procmail_yet
#define buggy_SENDMAIL
#define defPATH "PATH=$HOME/bin:/bin:/usr/bin:/usr/local/bin:/usr/bin/X11"
#define defSPATH "PATH=/bin:/usr/bin:/usr/local/bin:/usr/bin/X11"
#define PM_VERSION "3.22"
/*locktype: 4, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 4, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/*locktype: 6, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 6, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/*locktype: 7, countlocks: 0, timeout 0, watchdog 8, /tmp/_locktest*/
/*locktype: 7, countlocks: 0, timeout 0, watchdog 8, ./_locktest*/
/* Hotwire LOCKINGTEST=111 */
/* Procmail will lock via: dotlocking, fcntl(), lockf(), flock() */
#define USElockf
#define USEflock
/* autoconf completed */
