/* this file was autogenerated by make */
#define UCLIBC_TARGET_PREFIX  "/"
#define UCLIBC_DEVEL_PREFIX  "/home/changcs/usb-router-buildroot/build/staging_dir"
#define UCLIBC_BUILD_DIR  "/home/changcs/usb-router-buildroot/build/uClibc"
#define GCC_BIN  "/opt/brcm/hndtools-mipsel-linux-3.0/bin/mipsel-linux-gcc"
#define LIBGCC_DIR  "/projects/ntsw-sw/bcm47xx/brcm/hndtools-mipsel-linux/bin/../lib/gcc-lib/mipsel-linux/3.0/"
#define TARGET_ARCH  "mipsel"
#define DYNAMIC_LINKER  "/lib/ld-uClibc.so.0"
#define BUILD_DYNAMIC_LINKER  "/home/changcs/usb-router-buildroot/build/uClibc/lib/ld-uClibc.so.0"
#define __UCLIBC_HAS_MMU__ 1
#undef __HAS_ELF__
#define __UCLIBC_CTOR_DTOR__ 1
