/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_MIPS 1
#define CONFIG_MIPS32 1
#undef  CONFIG_MIPS64

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#undef  CONFIG_MODVERSIONS
#undef  CONFIG_KMOD

/*
 * Machine selection
 */
#undef  CONFIG_ACER_PICA_61
#undef  CONFIG_MIPS_DB1000
#undef  CONFIG_MIPS_DB1100
#undef  CONFIG_MIPS_DB1500
#undef  CONFIG_MIPS_PB1000
#undef  CONFIG_MIPS_PB1100
#undef  CONFIG_MIPS_PB1500
#undef  CONFIG_BAGET_MIPS
#undef  CONFIG_CASIO_E55
#undef  CONFIG_MIPS_COBALT
#undef  CONFIG_DECSTATION
#undef  CONFIG_MIPS_EV64120
#undef  CONFIG_MIPS_EV96100
#undef  CONFIG_MIPS_IVR
#undef  CONFIG_HP_LASERJET
#undef  CONFIG_IBM_WORKPAD
#undef  CONFIG_LASAT
#undef  CONFIG_MIPS_ITE8172
#undef  CONFIG_MIPS_ATLAS
#undef  CONFIG_MIPS_MAGNUM_4000
#undef  CONFIG_MIPS_MALTA
#undef  CONFIG_MIPS_SEAD
#undef  CONFIG_MOMENCO_OCELOT
#undef  CONFIG_MOMENCO_OCELOT_G
#undef  CONFIG_DDB5074
#undef  CONFIG_DDB5476
#undef  CONFIG_DDB5477
#undef  CONFIG_NEC_OSPREY
#undef  CONFIG_NEC_EAGLE
#undef  CONFIG_OLIVETTI_M700
#undef  CONFIG_NINO
#undef  CONFIG_SGI_IP22
#undef  CONFIG_SGI_IP27
#undef  CONFIG_SGI_IP32
#undef  CONFIG_SIBYTE_SB1xxx_SOC
#define CONFIG_MIPS_BRCM 1
#define CONFIG_BCM947XX 1
#define CONFIG_BCM4710 1
#define CONFIG_BCM4310 1
#define CONFIG_BCM4704 1
#undef  CONFIG_BCM5365
#undef  CONFIG_SNI_RM200_PCI
#undef  CONFIG_TOSHIBA_JMR3927
#undef  CONFIG_VICTOR_MPC30X
#undef  CONFIG_ZAO_CAPCELLA
#undef  CONFIG_HIGHMEM
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#undef  CONFIG_RWSEM_XCHGADD_ALGORITHM
#define CONFIG_CMDLINE "root=/dev/ram console=ttyS1,115200"
#define CONFIG_PCI 1
#define CONFIG_NONCOHERENT_IO 1
#define CONFIG_NEW_TIME_C 1
#define CONFIG_NEW_IRQ 1
#define CONFIG_HND 1
#undef  CONFIG_MIPS_AU1000

/*
 * CPU selection
 */
#define CONFIG_CPU_MIPS32 1
#undef  CONFIG_CPU_MIPS64
#undef  CONFIG_CPU_R3000
#undef  CONFIG_CPU_TX39XX
#undef  CONFIG_CPU_VR41XX
#undef  CONFIG_CPU_R4300
#undef  CONFIG_CPU_R4X00
#undef  CONFIG_CPU_TX49XX
#undef  CONFIG_CPU_R5000
#undef  CONFIG_CPU_R5432
#undef  CONFIG_CPU_R6000
#undef  CONFIG_CPU_NEVADA
#undef  CONFIG_CPU_R8000
#undef  CONFIG_CPU_R10000
#undef  CONFIG_CPU_RM7000
#undef  CONFIG_CPU_SB1
#define CONFIG_CPU_HAS_PREFETCH 1
#undef  CONFIG_VTAG_ICACHE
#undef  CONFIG_64BIT_PHYS_ADDR
#undef  CONFIG_CPU_ADVANCED
#define CONFIG_CPU_HAS_LLSC 1
#undef  CONFIG_CPU_HAS_LLDSCD
#undef  CONFIG_CPU_HAS_WB
#define CONFIG_CPU_HAS_SYNC 1

/*
 * General setup
 */
#define CONFIG_CPU_LITTLE_ENDIAN 1
#define CONFIG_NET 1
#undef  CONFIG_PCI_NAMES
#undef  CONFIG_ISA
#undef  CONFIG_EISA
#undef  CONFIG_TC
#undef  CONFIG_MCA
#undef  CONFIG_SBUS
#define CONFIG_HOTPLUG 1

/*
 * PCMCIA/CardBus support
 */
#undef  CONFIG_PCMCIA

/*
 * PCI Hotplug Support
 */
#undef  CONFIG_HOTPLUG_PCI
#undef  CONFIG_HOTPLUG_PCI_COMPAQ
#undef  CONFIG_HOTPLUG_PCI_COMPAQ_NVRAM
#undef  CONFIG_HOTPLUG_PCI_ACPI
#define CONFIG_SYSVIPC 1
#undef  CONFIG_BSD_PROCESS_ACCT
#define CONFIG_SYSCTL 1
#undef  CONFIG_PRINT_SYSCALLS
#define CONFIG_KCORE_ELF 1
#undef  CONFIG_KCORE_AOUT
#undef  CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_ELF 1
#undef  CONFIG_MIPS32_COMPAT
#undef  CONFIG_MIPS32_O32
#undef  CONFIG_MIPS32_N32
#undef  CONFIG_BINFMT_ELF32
#undef  CONFIG_BINFMT_MISC
#undef  CONFIG_PM

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD 1
#undef  CONFIG_MTD_DEBUG
#define CONFIG_MTD_PARTITIONS 1
#undef  CONFIG_MTD_CONCAT
#undef  CONFIG_MTD_REDBOOT_PARTS

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR 1
#define CONFIG_MTD_BLOCK 1
#undef  CONFIG_FTL
#undef  CONFIG_NFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI 1
#undef  CONFIG_MTD_JEDECPROBE
#define CONFIG_MTD_GEN_PROBE 1
#define CONFIG_MTD_CFI_ADV_OPTIONS 1
#define CONFIG_MTD_CFI_NOSWAP 1
#undef  CONFIG_MTD_CFI_BE_BYTE_SWAP
#undef  CONFIG_MTD_CFI_LE_BYTE_SWAP
#define CONFIG_MTD_CFI_GEOMETRY 1
#undef  CONFIG_MTD_CFI_B1
#define CONFIG_MTD_CFI_B2 1
#undef  CONFIG_MTD_CFI_B4
#define CONFIG_MTD_CFI_I1 1
#undef  CONFIG_MTD_CFI_I2
#undef  CONFIG_MTD_CFI_I4
#define CONFIG_MTD_CFI_INTELEXT 1
#define CONFIG_MTD_CFI_AMDSTD 1
#undef  CONFIG_MTD_CFI_SSTSTD
#undef  CONFIG_MTD_RAM
#undef  CONFIG_MTD_ROM
#undef  CONFIG_MTD_ABSENT
#undef  CONFIG_MTD_OBSOLETE_CHIPS
#undef  CONFIG_MTD_AMDSTD
#undef  CONFIG_MTD_SHARP
#undef  CONFIG_MTD_JEDEC

/*
 * Mapping drivers for chip access
 */
#undef  CONFIG_MTD_PHYSMAP
#define CONFIG_MTD_BCM947XX 1
#undef  CONFIG_MTD_PB1000
#undef  CONFIG_MTD_PB1500
#undef  CONFIG_MTD_PB1100
#undef  CONFIG_MTD_CSTM_MIPS_IXX
#undef  CONFIG_MTD_OCELOT
#undef  CONFIG_MTD_LASAT
#undef  CONFIG_MTD_PCI

/*
 * Self-contained MTD device drivers
 */
#undef  CONFIG_MTD_SFLASH
#undef  CONFIG_MTD_PMC551
#undef  CONFIG_MTD_SLRAM
#undef  CONFIG_MTD_MTDRAM
#undef  CONFIG_MTD_BLKMTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef  CONFIG_MTD_DOC1000
#undef  CONFIG_MTD_DOC2000
#undef  CONFIG_MTD_DOC2001
#undef  CONFIG_MTD_DOCPROBE

/*
 * NAND Flash Device Drivers
 */
#undef  CONFIG_MTD_NAND

/*
 * Parallel port support
 */
#undef  CONFIG_PARPORT

/*
 * Plug and Play configuration
 */
#undef  CONFIG_PNP
#undef  CONFIG_ISAPNP

/*
 * Block devices
 */
#undef  CONFIG_BLK_DEV_MSYS
#undef  CONFIG_NOROOT
#undef  CONFIG_BLK_DEV_FD
#undef  CONFIG_BLK_DEV_XD
#undef  CONFIG_PARIDE
#undef  CONFIG_BLK_CPQ_DA
#undef  CONFIG_BLK_CPQ_CISS_DA
#undef  CONFIG_CISS_SCSI_TAPE
#undef  CONFIG_BLK_DEV_DAC960
#undef  CONFIG_BLK_DEV_UMEM
#define CONFIG_BLK_DEV_LOOP 1
#undef  CONFIG_BLK_DEV_NBD
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_SIZE (4096)
#define CONFIG_BLK_DEV_INITRD 1
#undef  CONFIG_BLK_STATS

/*
 * MIPS initrd options
 */
#define CONFIG_EMBEDDED_RAMDISK 1
#define CONFIG_EMBEDDED_RAMDISK_IMAGE "ramdisk.gz"

/*
 * Multi-device support (RAID and LVM)
 */
#undef  CONFIG_MD
#undef  CONFIG_BLK_DEV_MD
#undef  CONFIG_MD_LINEAR
#undef  CONFIG_MD_RAID0
#undef  CONFIG_MD_RAID1
#undef  CONFIG_MD_RAID5
#undef  CONFIG_MD_MULTIPATH
#undef  CONFIG_BLK_DEV_LVM

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef  CONFIG_PACKET_MMAP
#undef  CONFIG_NETLINK_DEV
#define CONFIG_NETFILTER 1
#undef  CONFIG_NETFILTER_DEBUG
#undef  CONFIG_FILTER
#define CONFIG_UNIX 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#undef  CONFIG_IP_ADVANCED_ROUTER
#undef  CONFIG_IP_PNP
#undef  CONFIG_NET_IPIP
#undef  CONFIG_NET_IPGRE
#undef  CONFIG_IP_MROUTE
#undef  CONFIG_ARPD
#undef  CONFIG_INET_ECN
#undef  CONFIG_SYN_COOKIES

/*
 *   IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK 1
#define CONFIG_IP_NF_FTP 1
#define CONFIG_IP_NF_TFTP 1
#define CONFIG_IP_NF_TALK 1
#define CONFIG_IP_NF_H323 1
#undef  CONFIG_IP_NF_AMANDA
#define CONFIG_IP_NF_IRC 1
#define CONFIG_IP_NF_QUAKE3 1
#define CONFIG_IP_NF_CT_PROTO_GRE 1
#define CONFIG_IP_NF_PPTP 1
#define CONFIG_IP_NF_MMS 1
#define CONFIG_IP_NF_QUEUE 1
#define CONFIG_IP_NF_IPTABLES 1
#define CONFIG_IP_NF_MATCH_LIMIT 1
#undef  CONFIG_IP_NF_MATCH_QUOTA
#define CONFIG_IP_NF_MATCH_MAC 1
#undef  CONFIG_IP_NF_MATCH_PKTTYPE
#define CONFIG_IP_NF_MATCH_MARK 1
#define CONFIG_IP_NF_MATCH_MULTIPORT 1
#define CONFIG_IP_NF_MATCH_TOS 1
#define CONFIG_IP_NF_MATCH_ECN 1
#define CONFIG_IP_NF_MATCH_DSCP 1
#define CONFIG_IP_NF_MATCH_AH_ESP 1
#define CONFIG_IP_NF_MATCH_LENGTH 1
#define CONFIG_IP_NF_MATCH_TTL 1
#define CONFIG_IP_NF_MATCH_TCPMSS 1
#define CONFIG_IP_NF_MATCH_HELPER 1
#define CONFIG_IP_NF_MATCH_STATE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK 1
#define CONFIG_IP_NF_MATCH_UNCLEAN 1
#define CONFIG_IP_NF_MATCH_OWNER 1
#define CONFIG_IP_NF_FILTER 1
#define CONFIG_IP_NF_TARGET_REJECT 1
#define CONFIG_IP_NF_TARGET_MIRROR 1
#define CONFIG_IP_NF_NAT 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE 1
#define CONFIG_IP_NF_TARGET_REDIRECT 1
#define CONFIG_IP_NF_NAT_TALK 1
#define CONFIG_IP_NF_NAT_H323 1
#undef  CONFIG_IP_NF_NAT_LOCAL
#define CONFIG_IP_NF_NAT_SNMP_BASIC 1
#define CONFIG_IP_NF_NAT_IRC 1
#define CONFIG_IP_NF_NAT_QUAKE3 1
#define CONFIG_IP_NF_NAT_MMS 1
#define CONFIG_IP_NF_NAT_FTP 1
#define CONFIG_IP_NF_NAT_TFTP 1
#define CONFIG_IP_NF_NAT_PPTP 1
#define CONFIG_IP_NF_NAT_PROTO_GRE 1
#define CONFIG_IP_NF_MANGLE 1
#define CONFIG_IP_NF_TARGET_TOS 1
#define CONFIG_IP_NF_TARGET_ECN 1
#define CONFIG_IP_NF_TARGET_DSCP 1
#define CONFIG_IP_NF_TARGET_MARK 1
#define CONFIG_IP_NF_TARGET_LOG 1
#define CONFIG_IP_NF_TARGET_ULOG 1
#define CONFIG_IP_NF_TARGET_TCPMSS 1
#define CONFIG_IP_NF_ARPTABLES 1
#define CONFIG_IP_NF_ARPFILTER 1
#undef  CONFIG_IPV6
#undef  CONFIG_KHTTPD
#undef  CONFIG_ATM
#define CONFIG_VLAN_8021Q 1

/*
 *  
 */
#undef  CONFIG_IPX
#undef  CONFIG_ATALK

/*
 * Appletalk devices
 */
#undef  CONFIG_DEV_APPLETALK
#undef  CONFIG_DECNET
#define CONFIG_BRIDGE 1
#undef  CONFIG_X25
#undef  CONFIG_LAPB
#undef  CONFIG_LLC
#undef  CONFIG_NET_DIVERT
#undef  CONFIG_ECONET
#undef  CONFIG_WAN_ROUTER
#undef  CONFIG_NET_FASTROUTE
#undef  CONFIG_NET_HW_FLOWCONTROL

/*
 * QoS and/or fair queueing
 */
#undef  CONFIG_NET_SCHED

/*
 * Network testing
 */
#undef  CONFIG_NET_PKTGEN
#undef  CONFIG_IPSEC
#define CONFIG_IPSEC_MODULE 1

/*
 * IPSec options (FreeS/WAN)
 */
#define CONFIG_IPSEC_IPIP 1
#define CONFIG_IPSEC_AH 1
#define CONFIG_IPSEC_AUTH_HMAC_MD5 1
#define CONFIG_IPSEC_AUTH_HMAC_SHA1 1
#define CONFIG_IPSEC_ESP 1
#define CONFIG_IPSEC_ENC_3DES 1
#undef  CONFIG_IPSEC_IPCOMP
#define CONFIG_IPSEC_DEBUG 1
#define CONFIG_IPSEC_NAT_TRAVERSAL 1

/*
 * Telephony Support
 */
#undef  CONFIG_PHONE
#undef  CONFIG_PHONE_IXJ
#undef  CONFIG_PHONE_IXJ_PCMCIA

/*
 * ATA/IDE/MFM/RLL support
 */
#undef  CONFIG_IDE
#undef  CONFIG_BLK_DEV_IDE_MODES
#undef  CONFIG_BLK_DEV_HD

/*
 * SCSI support
 */
#undef  CONFIG_SCSI
#define CONFIG_SCSI_MODULE 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#undef  CONFIG_BLK_DEV_SD
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_SD_EXTRA_DEVS (40)
#undef  CONFIG_CHR_DEV_ST
#undef  CONFIG_CHR_DEV_OSST
#undef  CONFIG_BLK_DEV_SR
#undef  CONFIG_CHR_DEV_SG

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef  CONFIG_SCSI_DEBUG_QUEUES
#undef  CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#undef  CONFIG_SCSI_LOGGING

/*
 * SCSI low-level drivers
 */
#undef  CONFIG_BLK_DEV_3W_XXXX_RAID
#undef  CONFIG_SCSI_7000FASST
#undef  CONFIG_SCSI_ACARD
#undef  CONFIG_SCSI_AHA152X
#undef  CONFIG_SCSI_AHA1542
#undef  CONFIG_SCSI_AHA1740
#undef  CONFIG_SCSI_AACRAID
#undef  CONFIG_SCSI_AIC7XXX
#undef  CONFIG_SCSI_AIC7XXX_OLD
#undef  CONFIG_SCSI_DPT_I2O
#undef  CONFIG_SCSI_ADVANSYS
#undef  CONFIG_SCSI_IN2000
#undef  CONFIG_SCSI_AM53C974
#undef  CONFIG_SCSI_MEGARAID
#undef  CONFIG_SCSI_BUSLOGIC
#undef  CONFIG_SCSI_CPQFCTS
#undef  CONFIG_SCSI_DMX3191D
#undef  CONFIG_SCSI_DTC3280
#undef  CONFIG_SCSI_EATA
#undef  CONFIG_SCSI_EATA_DMA
#undef  CONFIG_SCSI_EATA_PIO
#undef  CONFIG_SCSI_FUTURE_DOMAIN
#undef  CONFIG_SCSI_GDTH
#undef  CONFIG_SCSI_GENERIC_NCR5380
#undef  CONFIG_SCSI_INITIO
#undef  CONFIG_SCSI_INIA100
#undef  CONFIG_SCSI_NCR53C406A
#undef  CONFIG_SCSI_NCR53C7xx
#undef  CONFIG_SCSI_SYM53C8XX_2
#undef  CONFIG_SCSI_NCR53C8XX
#undef  CONFIG_SCSI_SYM53C8XX
#undef  CONFIG_SCSI_PAS16
#undef  CONFIG_SCSI_PCI2000
#undef  CONFIG_SCSI_PCI2220I
#undef  CONFIG_SCSI_PSI240I
#undef  CONFIG_SCSI_QLOGIC_FAS
#undef  CONFIG_SCSI_QLOGIC_ISP
#undef  CONFIG_SCSI_QLOGIC_FC
#undef  CONFIG_SCSI_QLOGIC_1280
#undef  CONFIG_SCSI_SIM710
#undef  CONFIG_SCSI_SYM53C416
#undef  CONFIG_SCSI_DC390T
#undef  CONFIG_SCSI_T128
#undef  CONFIG_SCSI_U14_34F
#undef  CONFIG_SCSI_DEBUG

/*
 * I2O device support
 */
#undef  CONFIG_I2O
#undef  CONFIG_I2O_PCI
#undef  CONFIG_I2O_BLOCK
#undef  CONFIG_I2O_LAN
#undef  CONFIG_I2O_SCSI
#undef  CONFIG_I2O_PROC

/*
 * Network device support
 */
#define CONFIG_NETDEVICES 1

/*
 * Broadcom HND network devices
 */
#define CONFIG_HND 1
#undef  CONFIG_IL
#undef  CONFIG_ET
#define CONFIG_ET_MODULE 1
#undef  CONFIG_ET_4413
#define CONFIG_ET_47XX 1
#undef  CONFIG_ROBO
#define CONFIG_ROBO_MODULE 1
#undef  CONFIG_WL

/*
 * ARCnet devices
 */
#undef  CONFIG_ARCNET
#undef  CONFIG_DUMMY
#undef  CONFIG_BONDING
#undef  CONFIG_EQUALIZER
#undef  CONFIG_TUN
#undef  CONFIG_ETHERTAP

/*
 * Ethernet (10 or 100Mbit)
 */
#undef  CONFIG_NET_ETHERNET

/*
 * Ethernet (1000 Mbit)
 */
#undef  CONFIG_ACENIC
#undef  CONFIG_DL2K
#undef  CONFIG_E1000
#undef  CONFIG_MYRI_SBUS
#undef  CONFIG_NS83820
#undef  CONFIG_HAMACHI
#undef  CONFIG_YELLOWFIN
#undef  CONFIG_SK98LIN
#undef  CONFIG_TIGON3
#undef  CONFIG_FDDI
#undef  CONFIG_HIPPI
#undef  CONFIG_PLIP
#undef  CONFIG_PPP
#define CONFIG_PPP_MODULE 1
#undef  CONFIG_PPP_MULTILINK
#undef  CONFIG_PPP_FILTER
#undef  CONFIG_PPP_ASYNC
#define CONFIG_PPP_ASYNC_MODULE 1
#undef  CONFIG_PPP_SYNC_TTY
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#undef  CONFIG_PPP_DEFLATE
#undef  CONFIG_PPP_BSDCOMP
#undef  CONFIG_PPPOE
#define CONFIG_PPPOE_MODULE 1
#undef  CONFIG_SLIP

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1
#undef  CONFIG_STRIP
#undef  CONFIG_WAVELAN
#undef  CONFIG_ARLAN
#undef  CONFIG_AIRONET4500
#undef  CONFIG_AIRONET4500_NONCS
#undef  CONFIG_AIRONET4500_PROC
#undef  CONFIG_AIRO
#undef  CONFIG_HERMES
#undef  CONFIG_PLX_HERMES
#undef  CONFIG_PCI_HERMES
#define CONFIG_NET_WIRELESS 1

/*
 * Token Ring devices
 */
#undef  CONFIG_TR
#undef  CONFIG_NET_FC
#undef  CONFIG_RCPCI
#undef  CONFIG_SHAPER

/*
 * Wan interfaces
 */
#undef  CONFIG_WAN

/*
 * Amateur Radio support
 */
#undef  CONFIG_HAMRADIO

/*
 * IrDA (infrared) support
 */
#undef  CONFIG_IRDA

/*
 * ISDN subsystem
 */
#undef  CONFIG_ISDN

/*
 * Input core support
 */
#undef  CONFIG_INPUT
#undef  CONFIG_INPUT_KEYBDEV
#undef  CONFIG_INPUT_MOUSEDEV
#undef  CONFIG_INPUT_JOYDEV
#undef  CONFIG_INPUT_EVDEV

/*
 * Character devices
 */
#undef  CONFIG_VT
#define CONFIG_SERIAL 1
#define CONFIG_SERIAL_CONSOLE 1
#undef  CONFIG_SERIAL_EXTENDED
#define CONFIG_SERIAL_NONSTANDARD 1
#undef  CONFIG_COMPUTONE
#undef  CONFIG_ROCKETPORT
#undef  CONFIG_CYCLADES
#undef  CONFIG_DIGIEPCA
#undef  CONFIG_DIGI
#undef  CONFIG_ESPSERIAL
#undef  CONFIG_MOXA_INTELLIO
#undef  CONFIG_MOXA_SMARTIO
#undef  CONFIG_ISI
#undef  CONFIG_SYNCLINK
#undef  CONFIG_SYNCLINKMP
#undef  CONFIG_N_HDLC
#define CONFIG_N_HDLC_MODULE 1
#undef  CONFIG_RISCOM8
#undef  CONFIG_SPECIALIX
#undef  CONFIG_SX
#undef  CONFIG_RIO
#undef  CONFIG_STALDRV
#undef  CONFIG_SERIAL_TX3912
#undef  CONFIG_SERIAL_TX3912_CONSOLE
#undef  CONFIG_TXX927_SERIAL
#undef  CONFIG_UNIX98_PTYS

/*
 * I2C support
 */
#undef  CONFIG_I2C

/*
 * Mice
 */
#undef  CONFIG_BUSMOUSE
#undef  CONFIG_MOUSE

/*
 * Joysticks
 */
#undef  CONFIG_INPUT_GAMEPORT

/*
 * Input core support is needed for gameports
 */

/*
 * Input core support is needed for joysticks
 */
#undef  CONFIG_QIC02_TAPE

/*
 * Watchdog Cards
 */
#undef  CONFIG_WATCHDOG
#undef  CONFIG_AMD_PM768
#undef  CONFIG_NVRAM
#undef  CONFIG_RTC
#undef  CONFIG_DTLK
#undef  CONFIG_R3964
#undef  CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef  CONFIG_FTAPE
#undef  CONFIG_AGP
#undef  CONFIG_DRM

/*
 * File systems
 */
#undef  CONFIG_QUOTA
#undef  CONFIG_AUTOFS_FS
#undef  CONFIG_AUTOFS4_FS
#undef  CONFIG_REISERFS_FS
#undef  CONFIG_REISERFS_CHECK
#undef  CONFIG_REISERFS_PROC_INFO
#undef  CONFIG_ADFS_FS
#undef  CONFIG_ADFS_FS_RW
#undef  CONFIG_AFFS_FS
#undef  CONFIG_HFS_FS
#undef  CONFIG_BEFS_FS
#undef  CONFIG_BEFS_DEBUG
#undef  CONFIG_BFS_FS
#undef  CONFIG_EXT3_FS
#undef  CONFIG_JBD
#undef  CONFIG_JBD_DEBUG
#define CONFIG_FAT_FS 1
#define CONFIG_MSDOS_FS 1
#undef  CONFIG_UMSDOS_FS
#define CONFIG_VFAT_FS 1
#undef  CONFIG_EFS_FS
#undef  CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS 1
#define CONFIG_JFFS2_FS_DEBUG (0)
#undef  CONFIG_CRAMFS
#define CONFIG_TMPFS 1
#define CONFIG_RAMFS 1
#undef  CONFIG_ISO9660_FS
#undef  CONFIG_JOLIET
#undef  CONFIG_ZISOFS
#undef  CONFIG_JFS_FS
#undef  CONFIG_JFS_DEBUG
#undef  CONFIG_JFS_STATISTICS
#define CONFIG_MINIX_FS 1
#undef  CONFIG_VXFS_FS
#define CONFIG_NTFS_FS 1
#undef  CONFIG_NTFS_RW
#undef  CONFIG_HPFS_FS
#define CONFIG_PROC_FS 1
#undef  CONFIG_DEVFS_FS
#undef  CONFIG_DEVFS_MOUNT
#undef  CONFIG_DEVFS_DEBUG
#undef  CONFIG_DEVPTS_FS
#undef  CONFIG_QNX4FS_FS
#undef  CONFIG_QNX4FS_RW
#undef  CONFIG_ROMFS_FS
#undef  CONFIG_EXT2_FS
#undef  CONFIG_SYSV_FS
#undef  CONFIG_UDF_FS
#undef  CONFIG_UDF_RW
#undef  CONFIG_UFS_FS
#undef  CONFIG_UFS_FS_WRITE

/*
 * Network File Systems
 */
#undef  CONFIG_CODA_FS
#undef  CONFIG_INTERMEZZO_FS
#undef  CONFIG_NFS_FS
#undef  CONFIG_NFS_V3
#undef  CONFIG_ROOT_NFS
#undef  CONFIG_NFSD
#undef  CONFIG_NFSD_V3
#undef  CONFIG_NFSD_TCP
#undef  CONFIG_SUNRPC
#undef  CONFIG_LOCKD
#undef  CONFIG_SMB_FS
#undef  CONFIG_NCP_FS
#undef  CONFIG_NCPFS_PACKET_SIGNING
#undef  CONFIG_NCPFS_IOCTL_LOCKING
#undef  CONFIG_NCPFS_STRONG
#undef  CONFIG_NCPFS_NFS_NS
#undef  CONFIG_NCPFS_OS2_NS
#undef  CONFIG_NCPFS_SMALLDOS
#undef  CONFIG_NCPFS_NLS
#undef  CONFIG_NCPFS_EXTRAS
#undef  CONFIG_ZISOFS_FS

/*
 * Partition Types
 */
#undef  CONFIG_PARTITION_ADVANCED
#define CONFIG_MSDOS_PARTITION 1
#undef  CONFIG_SMB_NLS
#define CONFIG_NLS 1

/*
 * Native Language Support
 */
#define CONFIG_NLS_DEFAULT "iso8859-1"
#undef  CONFIG_NLS_CODEPAGE_437
#undef  CONFIG_NLS_CODEPAGE_737
#undef  CONFIG_NLS_CODEPAGE_775
#undef  CONFIG_NLS_CODEPAGE_850
#undef  CONFIG_NLS_CODEPAGE_852
#undef  CONFIG_NLS_CODEPAGE_855
#undef  CONFIG_NLS_CODEPAGE_857
#undef  CONFIG_NLS_CODEPAGE_860
#undef  CONFIG_NLS_CODEPAGE_861
#undef  CONFIG_NLS_CODEPAGE_862
#undef  CONFIG_NLS_CODEPAGE_863
#undef  CONFIG_NLS_CODEPAGE_864
#undef  CONFIG_NLS_CODEPAGE_865
#undef  CONFIG_NLS_CODEPAGE_866
#undef  CONFIG_NLS_CODEPAGE_869
#undef  CONFIG_NLS_CODEPAGE_936
#undef  CONFIG_NLS_CODEPAGE_950
#undef  CONFIG_NLS_CODEPAGE_932
#undef  CONFIG_NLS_CODEPAGE_949
#undef  CONFIG_NLS_CODEPAGE_874
#undef  CONFIG_NLS_ISO8859_8
#undef  CONFIG_NLS_CODEPAGE_1250
#undef  CONFIG_NLS_CODEPAGE_1251
#undef  CONFIG_NLS_ISO8859_1
#undef  CONFIG_NLS_ISO8859_2
#undef  CONFIG_NLS_ISO8859_3
#undef  CONFIG_NLS_ISO8859_4
#undef  CONFIG_NLS_ISO8859_5
#undef  CONFIG_NLS_ISO8859_6
#undef  CONFIG_NLS_ISO8859_7
#undef  CONFIG_NLS_ISO8859_9
#undef  CONFIG_NLS_ISO8859_13
#undef  CONFIG_NLS_ISO8859_14
#undef  CONFIG_NLS_ISO8859_15
#undef  CONFIG_NLS_KOI8_R
#undef  CONFIG_NLS_KOI8_U
#undef  CONFIG_NLS_UTF8

/*
 * Multimedia devices
 */
#undef  CONFIG_VIDEO_DEV

/*
 * Sound
 */
#undef  CONFIG_SOUND

/*
 * USB support
 */
#undef  CONFIG_USB
#define CONFIG_USB_MODULE 1
#undef  CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef  CONFIG_USB_BANDWIDTH
#undef  CONFIG_USB_LONG_TIMEOUT

/*
 * USB Host Controller Drivers
 */
#undef  CONFIG_USB_EHCI_HCD
#define CONFIG_USB_EHCI_HCD_MODULE 1
#undef  CONFIG_USB_UHCI
#undef  CONFIG_USB_UHCI_ALT
#undef  CONFIG_USB_OHCI
#define CONFIG_USB_OHCI_MODULE 1

/*
 * USB Device Class drivers
 */
#undef  CONFIG_USB_AUDIO
#undef  CONFIG_USB_EMI26
#undef  CONFIG_USB_BLUETOOTH
#undef  CONFIG_USB_MIDI
#undef  CONFIG_USB_STORAGE
#define CONFIG_USB_STORAGE_MODULE 1
#undef  CONFIG_USB_STORAGE_DEBUG
#undef  CONFIG_USB_STORAGE_DATAFAB
#undef  CONFIG_USB_STORAGE_FREECOM
#undef  CONFIG_USB_STORAGE_ISD200
#undef  CONFIG_USB_STORAGE_DPCM
#undef  CONFIG_USB_STORAGE_HP8200e
#undef  CONFIG_USB_STORAGE_SDDR09
#undef  CONFIG_USB_STORAGE_SDDR55
#undef  CONFIG_USB_STORAGE_JUMPSHOT
#undef  CONFIG_USB_ACM
#undef  CONFIG_USB_PRINTER

/*
 * USB Human Interface Devices (HID)
 */
#undef  CONFIG_USB_HID

/*
 *     Input core support is needed for USB HID input layer or HIDBP support
 */
#undef  CONFIG_USB_HIDINPUT
#undef  CONFIG_USB_HIDDEV
#undef  CONFIG_USB_KBD
#undef  CONFIG_USB_MOUSE
#undef  CONFIG_USB_AIPTEK
#undef  CONFIG_USB_WACOM

/*
 * USB Imaging devices
 */
#undef  CONFIG_USB_DC2XX
#undef  CONFIG_USB_MDC800
#undef  CONFIG_USB_SCANNER
#undef  CONFIG_USB_MICROTEK
#undef  CONFIG_USB_HPUSBSCSI

/*
 * USB Multimedia devices
 */

/*
 *   Video4Linux support is needed for USB Multimedia device support
 */

/*
 * USB Network adaptors
 */
#undef  CONFIG_USB_PEGASUS
#undef  CONFIG_USB_RTL8150
#undef  CONFIG_USB_KAWETH
#undef  CONFIG_USB_CATC
#undef  CONFIG_USB_CDCETHER
#undef  CONFIG_USB_USBNET

/*
 * USB port drivers
 */
#undef  CONFIG_USB_USS720

/*
 * USB Serial Converter support
 */
#undef  CONFIG_USB_SERIAL

/*
 * USB Miscellaneous drivers
 */
#undef  CONFIG_USB_RIO500
#undef  CONFIG_USB_AUERSWALD
#undef  CONFIG_USB_TIGL
#undef  CONFIG_USB_BRLVGER
#undef  CONFIG_USB_LCD

/*
 * Support for USB gadgets
 */
#undef  CONFIG_USB_GADGET

/*
 * Bluetooth support
 */
#undef  CONFIG_BLUEZ

/*
 * Kernel hacking
 */
#define CONFIG_CROSSCOMPILE 1
#undef  CONFIG_KERNPROF
#undef  CONFIG_MCOUNT
#undef  CONFIG_DEBUG
#define CONFIG_MAGIC_SYSRQ 1
#undef  CONFIG_MIPS_UNCACHED
#undef  CONFIG_KTRACE
#undef  CONFIG_HWSIM

/*
 * Library routines
 */
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE 1
