/* include/config.h.  Generated by configure.  */
#ident "$Id: config.h.in,v 1.4 2004/02/03 15:23:21 raven Exp $"
/* -*- c -*-
 *
 * config.h.in: Pattern file for autofs to be filled in by configure
 *
 */

/* Program paths */
#define HAVE_MOUNT 1
#define PATH_MOUNT "/bin/mount"

#define HAVE_UMOUNT 1
#define PATH_UMOUNT "/bin/umount"

/* #undef HAVE_SMBMOUNT */
/* #undef PATH_SMBMOUNT */

#define HAVE_E2FSCK 1
#define PATH_E2FSCK "/sbin/fsck.ext2"

#define HAVE_E3FSCK 1
#define PATH_E3FSCK "/sbin/fsck.ext3"

/* Define this option if mount(8) supports the -s (sloppy) option */
/* #undef HAVE_SLOPPY_MOUNT */

/* #undef ENABLE_EXT_ENV */
