.SH INET6 ADDRESS FAMILY
This section documents the methods available in the
inet6 address family.
.SS The loopback Method
This method may be used to define the IPv6 loopback interface. 
.PP
.B Options
.RS
.TP
(No options)
.RE
.SS The static Method
This method may be used to define interfaces with statically assigned IPv6 addresses. 
.PP
.B Options
.RS
.TP
.BI address " address       "
Address (colon delimited) \fBrequired\fP
.TP
.BI netmask " mask          "
Netmask (number of bits, eg 64) \fBrequired\fP
.TP
.BI gateway " address       "
Default gateway (colon delimited)
.TP
.BI media " type            "
Medium type, driver dependent
.TP
.BI hwaddress " class address"
Hardware Address. \fIclass\fP is one of \fBether\fP, \fBax25\fP, \fBARCnet\fP or \fBnetrom\fP. \fIaddress\fP is dependent on this choice.
.TP
.BI mtu " size              "
MTU size
.RE
.SS The v4tunnel Method
This method may be used to setup an IPv6-over-IPv4 tunnel. It requires the \fBip\fP command from the \fBiproute\fP package. 
.PP
.B Options
.RS
.TP
.BI address " address      "
Address (colon delimited) \fBrequired\fP
.TP
.BI netmask " mask         "
Netmask (number of bits, eg 64) \fBrequired\fP
.TP
.BI endpoint " address     "
Address of other tunnel endpoint (IPv4 dotted quad) \fBrequired\fP
.TP
.BI local " address        "
Address of the local endpoint (IPv4 dotted quad)
.TP
.BI gateway " address      "
Default gateway (colon delimited)
.TP
.BI ttl " time             "
TTL setting
.RE
